apiVersion: v2
description: A Helm chart for general app
home: https://github.com/machtwatch/helm-private-repo/tree/master/charts
name: app
sources:
- https://github.com/machtwatch/helm-private-repo/tree/master/charts
type: application
version: 0.1.5
